### ISSUE TITLE
No way to split into multiple files

### ISSUE THREAD

**Issue by rafaelmagu** [winebarrel/barkdog#8]
I've tried multiple Ruby ways of including other files into the Barkfile, all to no avail. It seems there's no way to split the monitors into multiple files for easier management.

**Comment by winebarrel** [comment]
You can split the file in the following way.
- file1.rb

``` rb
monitor "Check load avg", :type=>"metric alert" do
  query "avg(last_5m):avg:ddstat.load_avg.1m{host:i-XXXXXXXX} > 1"
  message "@winebarrel@example.net"
  options do
    notify_no_data true
    no_data_timeframe 2
    notify_audit true
    silenced({})
  end
end
```
- file2.rb

``` rb
monitor "Check load avg2", :type=>"metric alert" do
  query "avg(last_1m):avg:ddstat.load_avg.1m{host:i-XXXXXXXX} > 1"
  message "@winebarrel@example.net"
  options do
    notify_no_data true
    no_data_timeframe 2
    notify_audit true
    silenced({})
  end
end
```
- Barkfile

``` rb
require 'file1'
require 'file2'
```

Is your problem solved?

**Comment by rafaelmagu** [comment]
Yup, after a little bit of trial and error, your suggestion got me on the right track. As it turns out, `require_relative` doesn't seem to work, spitting out:

```
Apply `datadog/Barkfile` to Datadog monitors (dry-run)
[ERROR] undefined method `monitor' for main:Object
```

Switched that to a simple `require` and all's good. 👍
